lint:  ;@echo "Linting ${PROJECT}....."; \
	./node_modules/.bin/eslint . --fix

run: ;@echo "Starting ${PROJECT}....."; \
	npm run dev

install: ;@echo "Installing ${PROJECT}....."; \
	npm install

clean : ;
	rm -rf node_modules